### ISSUE TITLE
What does 'subject' mean in the initialization function of serializer and how to use this package?

### ISSUE THREAD

**Issue by Reapor-Yurnero** [bakdata/faust-avro-serializer#4]
I don't understand what does the subject here mean. Should it be the same as the name of the schema?

By the way, I'm confused why in the example the MyRecordExample is never used and how it is related to the serializer. I tried to use `faust.topic("a", value_type=MyRecordExample)` but it seems it's wrong.

A more detailed example including how to use this with a simple faust application might be very helpful.

**Comment by philipp94831** [comment]
Hi @Reapor-Yurnero , we updated the README. With regard to your question, what a subject is, we refer to the [official documentation](https://docs.confluent.io/current/schema-registry/index.html#schemas-subjects-and-topics)

**Comment by Reapor-Yurnero** [comment]
Thanks. I'm very glad that you finally respond. I once thought this repo is no longer maintained.
