### ISSUE TITLE
Should be `class MyRecordExample(faust.Record, serializer=serializer):`?

### ISSUE THREAD

**Issue by Reapor-Yurnero** [bakdata/faust-avro-serializer#5]
In the Example in the Readme, shouldn't the definition of the class MyRecordExample behind the definition of serializer and be something like `class MyRecordExample(faust.Record, serializer=serializer):`?

**Comment by philipp94831** [comment]
Hi @Reapor-Yurnero , we updated the README. Because we use a faust schema, the serializer in the record class is not needed
